Use of ${0##*/} instead of basename

diff --git a/colman b/colman
--- a/colman
+++ b/colman
@@ -116,7 +116,7 @@ update)
         if [ -d $HOME/.base16/base16-xresources ]; then
                 ( cd $HOME/.base16/base16-xresources; git pull )
         else
-                >&2 echo "$(basename $0): base16 xresources directory not found, please install it first"
+                >&2 echo "${0##*/}: base16 xresources directory not found, please install it first"
                 exit 1
         fi
         ;;
@@ -155,15 +155,15 @@ set)
                         change_color "$res" "$(xrdb -query | grep "XTerm\*$res:" | awk '{print $2}')"
                 done
         else
-                >&2 echo "$(basename $0): Missing or unknown colorscheme"
+                >&2 echo "${0##*/}: Missing or unknown colorscheme"
                 exit 1
         fi
         ;;
 help)
         ;;
 *)
-        >&2 echo "$(basename $0): Missing or unknown command"
-        >&2 echo "Try \"$(basename $0) help\" for more info"
+        >&2 echo "${0##*/}: Missing or unknown command"
+        >&2 echo "Try \"${0##*/} help\" for more info"
 esac
 
 exit 0
diff --git a/logan b/logan
--- a/logan
+++ b/logan
@@ -267,7 +267,7 @@ while getopts ":ht:p:c:g:o:i:" arg; do
                         #codePattern="\*[E,W],[A-Za-z0-9]+:"
                         ;;
                 *)
-                        >&2 echo "$(basename $0): Unknown tool: $OPTARG"
+                        >&2 echo "${0##*/}: Unknown tool: $OPTARG"
                         exit 1
                 esac
                 ;;
@@ -286,16 +286,16 @@ while getopts ":ht:p:c:g:o:i:" arg; do
         i)
                 ignoreFile="$OPTARG"
                 if [ ! -f "$ignoreFile" ]; then
-                        >&2 echo "$(basename $0): cannot stat $ignoreFile: No such file"
+                        >&2 echo "${0##*/}: cannot stat $ignoreFile: No such file"
                         exit 1
                 fi
                 ;;
         :)
-                echo "$(basename $0): Option -$OPTARG requires an argument"
+                echo "${0##*/}: Option -$OPTARG requires an argument"
                 exit 1
                 ;;
         \?)
-                echo "$(basename $0): Unknown option: -$OPTARG"
+                echo "${0##*/}: Unknown option: -$OPTARG"
                 exit 1
         esac
 done
@@ -303,22 +303,22 @@ shift $(($OPTIND - 1))
 
 # Remaining positional argument is supposed to be the logFile
 if [ "$#" -ne 1 ]; then
-        >&2 echo "$(basename $0): Missing logFile"
-        >&2 echo "Try \"$(basename $0) -h\" for more info"
+        >&2 echo "${0##*/}: Missing logFile"
+        >&2 echo "Try \"${0##*/} -h\" for more info"
         exit 1
 fi
 logFile="$1"
 
 # Check if logFile exists
 if [ ! -f "$logFile" ]; then
-        >&2 echo "$(basename $0): cannot stat $logFile: No such file"
+        >&2 echo "${0##*/}: cannot stat $logFile: No such file"
         exit 1
 fi
 
 # Check if pattern has been defined
 if [ -z "$pattern" ]; then
-        >&2 echo "$(basename $0): Missing pattern or tool"
-        >&2 echo "Try \"$(basename $0) -h\" for more info"
+        >&2 echo "${0##*/}: Missing pattern or tool"
+        >&2 echo "Try \"${0##*/} -h\" for more info"
         exit 1
 fi
 
