- Added _array function check for strict POSIX shells; - added a quirk for cwm (to be changed in an option?)

diff --git a/wmprocs b/wmprocs
--- a/wmprocs
+++ b/wmprocs
@@ -70,14 +70,15 @@ _help() {
 }
 
 _array() {
-        case "$SH_VERSION" in
-        *KSH*)
+        if [[ -n "$KSH_VERSION" || "$SH_VERSION" == *KSH* ]]; then
                 a="$1"; shift
                 set -A "$a" "$@"
-                ;;
-        *)
+        elif [ -n "$BASH_VERSION" ]; then
                 eval $1='("${@:2}")'
-        esac
+        else
+                >&2 echo "${0##*/}: Error: This shell doesn't support arrays"
+                exit 1
+        fi
 }
 
 get_actwin_id() {
@@ -102,9 +103,8 @@ get_curr_ws() {
 }
 
 get_viswin_ids() {
-        # Get visible window ids from current workspace and
-        # screen, excluding docks and panels
-        #
+        # Get visible window ids from current workspace (or set of
+        # active groups/tags) and screen, excluding docks and panels
         actwin_id=${1:-$(get_actwin_id)}
         curr_ws="$(get_curr_ws)"
         for win_id in $(get_win_ids)
@@ -113,7 +113,8 @@ get_viswin_ids() {
 			$(get_win_orig $win_id)
 		EOT
                 if [ "$win_id" != "$actwin_id" ] &&
-                   [ "$(xprop -id $win_id _NET_WM_DESKTOP | egrep -o "[0-9]+")" = "$curr_ws" ] &&
+                   (pgrep -x cwm >/dev/null ||
+                    [ "$(xprop -id $win_id _NET_WM_DESKTOP | egrep -o "[0-9]+")" = "$curr_ws" ]) &&
                    ! xprop -id $win_id _NET_WM_WINDOW_TYPE | egrep "DOCK|DESKTOP" >/dev/null 2>&1 &&
                    xprop -id $win_id WM_STATE | grep "window state" | grep "Normal" >/dev/null 2>&1 &&
                    [ $wo_x0 -ge $act_x0 ] && [ $wo_x0 -lt $(($act_x0 + $act_xdim)) ] &&
